### ISSUE TITLE
rename compileX to parseX?

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#101]
I just realized that the `compileStringLiteral` etc. functions are misnamed, since they only parse the node without doing any other part of compilation. Is it too late to change that?

**Comment by jvasileff** [comment]
I don't think it's too late. My expectation is that there would be (reasonable) compatibility breaks from time to time anyway, do to the nature of the module.

**Comment by lucaswerkmeister** [comment]
How about we do this in 1.3.0? That will probably include language changes and therefore be incompatible anyways.

(Of course, we can also supply a command that automatically updates source code from `compileX` to `parseX`, to aid upgrading.)

**Comment by lucaswerkmeister** [comment]
Well, 1.3.0 is coming up fast, so let’s see if we can’t get this done!

**Comment by lucaswerkmeister** [comment]
By the way, this also reduces `.car` size by 1.9% ;)
