### ISSUE TITLE
Bug processing typechecked `package` and `module` decs

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#105]
Section [6.10.2. Package and module references](http://ceylon-lang.org/documentation/1.2/spec/html_single/#packageandmodulereferences) allows package-name-less package reference expressions (`` `package` ``):

> If there is no explicit package name, the package reference is to the package in which the package reference expression occurs.

but `ceylon.ast.redhat` blows up with:

```
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated nonempty components = CeylonIterable(fullPackageName.identifiers).collect(propagateUpdate(pIdentifierToCeylon, update))"
	at ceylon.ast.redhat.fullPackageNameToCeylon_.fullPackageNameToCeylon(FullPackageName.ceylon:17)
	at ceylon.ast.redhat.packageDecToCeylon_.packageDecToCeylon(PackageDec.ceylon:16)
	at ceylon.ast.redhat.decToCeylon_.decToCeylon(Dec.ceylon:32)
	at ceylon.ast.redhat.primaryToCeylon_.primaryToCeylon(Primary.ceylon:47)
```

This is supported by the api of `PackageDec`, as `packageName` is optional.

**Comment by jvasileff** [comment]
@lucaswerkmeister re you're Gitter question

> it looks like you’ve managed to get a package literal with a non-null, but empty import path
how?

it must be that the type checker fills in this info when full type checking is performed. For the program:

```ceylon
Anything p = `package`;
```

I get:
```
$ ceylon compile-dart --verbose=ast,rhAst
...
-- Redhat AST simple/run.ceylon
+  [CompilationUnit] (1:0-1:22)
|  +  [ImportList]
|  +  [AttributeDeclaration] (1:0-1:22) : value p => Anything
|  |  +  [AnnotationList]
|  |  + p [Identifier] (1:9-1:9)
|  |  +  [BaseType] (1:0-1:7) : Anything : class Anything()
|  |  |  + Anything [Identifier] (1:0-1:7)
|  |  + = [SpecifierExpression] (1:11-1:21)
|  |  |  +  [Expression] (1:13-1:21) : Package
|  |  |  |  + `` [PackageLiteral] (1:13-1:21) : Package
|  |  |  |  |  +  [ImportPath]

------------------------------------------------------------
                    ** Compiler bug! **
------------------------------------------------------------
Assertion failed
	violated nonempty components = CeylonIterable(fullPackageName.identifiers).collect(propagateUpdate(pIdentifierToCeylon, update))

was encountered while compiling the file:

    source/simple/run.ceylon
------------------------------------------------------------
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated nonempty components = CeylonIterable(fullPackageName.identifiers).collect(propagateUpdate(pIdentifierToCeylon, update))"
	at ceylon.ast.redhat.fullPackageNameToCeylon_.fullPackageNameToCeylon(FullPackageName.ceylon:17)
	at ceylon.ast.redhat.packageDecToCeylon_.packageDecToCeylon(PackageDec.ceylon:16)
	at ceylon.ast.redhat.decToCeylon_.decToCeylon(Dec.ceylon:32)
```

**Comment by jvasileff** [comment]
Ah, looks like `ExpressionVisitor.java` is the `null` hater (or null burier?):

https://github.com/ceylon/ceylon/blob/3d92c0cb6faf9b5d2c93635f82b27ee1c8e26c89/typechecker/src/com/redhat/ceylon/compiler/typechecker/analyzer/ExpressionVisitor.java#L8841

Module literals may also be affected.

**Comment by lucaswerkmeister** [comment]
Indeed it does: [`ExpressionVisitor.java:8847`](https://github.com/ceylon/ceylon/blob/5072c1db8483b7b2c14d6ff43ed89a68f1649f59/typechecker/src/com/redhat/ceylon/compiler/typechecker/analyzer/ExpressionVisitor.java#L8845-L8849). I thought it would create a proper import path with the correct components, but it looks like it doesn’t. Alright.

**Comment by jvasileff** [comment]
Github tells me I beat you by 1s :)

**Comment by lucaswerkmeister** [comment]
GitHub doesn’t even tell me second-precise timestamps :(

**Comment by jvasileff** [comment]
So yes, `` `Anything p = `module`;` `` also fails with:
```
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated nonempty components = CeylonIterable(fullPackageName.identifiers).collect(propagateUpdate(pIdentifierToCeylon, update))"
	at ceylon.ast.redhat.fullPackageNameToCeylon_.fullPackageNameToCeylon(FullPackageName.ceylon:17)
	at ceylon.ast.redhat.moduleDecToCeylon_.moduleDecToCeylon(ModuleDec.ceylon:16)
	at ceylon.ast.redhat.decToCeylon_.decToCeylon(Dec.ceylon:33)
	at ceylon.ast.redhat.primaryToCeylon_.primaryToCeylon(Primary.ceylon:47)
```

**Comment by lucaswerkmeister** [comment]
Should be fixed in branch `fix105`, can you try it out?

(`` `class` `` and `` `interface` `` should be fine afaict.)

**Comment by jvasileff** [comment]
works great, thanks!

BTW, a nice tool for testing this sort of thing is `ceylon compile-dart --verbose=ast,rhAst` :)

**Comment by lucaswerkmeister** [comment]
Alright, pushed to master then :)

And it seems like your compiler is a great way to debug ceylon.ast on
typechecked ASTs, so I guess I’ll install it :D
