### ISSUE TITLE
consider optimized approach to 'extraInfo'

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#108]
ExtraInfo is made available through two generic methods, `Type? get<out Type>(Key<out Type> key)` and `void putVoid<Type>(Key<Type> key, Type item)`. Both of these methods perform type checks using a type parameter (e.g. `assert (is Type ret)`). Unfortunately, this pattern can be *very* slow, even for non-generic `Type`s. And even if backend improvements make this *reasonably fast*, it still may not be fast enough for this use case.

As a test, adding and using `Node` methods:

```ceylon
    shared Object? getRaw(Key<out Anything> key) {
        return extraInfo[key.id];
    }

    shared void putVoid<Type>(Key<Type> key, Type item)
            given Type satisfies Object {
        extraInfo.put(key.id, item);
    }
```

resulted in over 40% total time reduction in Dart backend code transformation, after warmup, for 7 sdk modules (2389ms vs 4280ms).

I'm *not* proposing we just add methods with these ugly names, but instead I'm opening this issue to investigate solutions. The current design is quite nice, but also expensive.

BTW, I also thought of using my own `MutableMap<Node, Data>` as a workaround, but that's not feasible today due to `Node.equals()` performance, which I'm not sure can be fixed without 1) making nodes `Identifiable`, 2) adding an `Identifiable` marker to each concrete node, or 3) sharing the extra info map, to be used as a surrogate identity.

**Comment by lucaswerkmeister** [comment]
I believe `putVoid` is called `set` :)

**Comment by jvasileff** [comment]
> I believe putVoid is called set :)

haha. The very next method after my `putVoid()` impl, and the one after `put()`, with `put` having a `see(set)` annotation!

**Comment by lucaswerkmeister** [comment]
And don’t forget the documentation on `put`!

**Comment by jvasileff** [comment]
It turns out there are many variables affecting reified generics performance, such as if `T` is a Ceylon or java type, if `T` matches *exactly* the class of the instance or if the instance is a subtype, etc.

In some initial testing, I've found that code similar to `get` with a non-generic `T` that is a Java class performs slightly faster than a HashMap lookup after warmup and at scale (11 to 13 nanos). I'm also suspicious of these results; the reified check seems too fast to be believable based on the impact it has on real world code.

Nevertheless, I'll make some preliminary observations:

1. A partial workaround for the performance problem *might* be to create a `final` *Ceylon* container class for the object to be stored. This seems to be the ideal scenario for reified generics performance. Of course, this would be an ugly thing to officially recommend.
2. Idea: add a `shared variable Anything data = null` attribute to `Node` that is documented for use by highly performance critical applications.

Item 2 has the potential to be a huge performance win, saving both the reified check and the map lookup. It also aligns with my use case where the type safety offered by the extra info design is largely unappreciated: I'm storing typechecker nodes of various types, but with a single key of the root tc node type. And then, based on the AST node type, I narrow the typechecker node with `assert` after `get` as necessary.

**Comment by lucaswerkmeister** [comment]
1. Interesting…
   > Of course, this would be an ugly thing to officially recommend.
   
   I don’t see why this would be an official recommendation… wouldn’t `ceylon.ast` do this under the covers, wrapping in `put`/`set` and unwrapping in `put`/`get`? Or do you think this choice should be left to library users?

2. In principle, I’m not even opposed to adding multiple, application-specific fields like that if the application is sufficiently important (and a compiler backend definitely qualifies as important, as would the typechecker if it was ever ported). Would it be useful to you if I provided multiple fields? (I guess the use would be limited at best since I can’t give them static types without depending on unwanted modules.)

Also, we should definitely add `getRaw` as counterpart to `set`. Any ideas for a better name?

**Comment by lucaswerkmeister** [comment]
> I don’t see why this would be an official recommendation…

Oh no, I see, for `get`/`put` we still need a reified test *somewhere* of course. This only applies if the type you store in the node is final. I’m a moron.

**Comment by jvasileff** [comment]
> Idea: add a shared variable Anything data = null attribute to Node

I tried this out. The results were about what I expected, 3585ms vs. 2324ms. Note, this is with the *latest* Dart backend code, different than what was used for prior measurements.

This is a very nice improvement, but does not indicate a big improvement from avoiding the `HashMap`, bringing further into question my micro-benchmark results showing a near equivalence to performance cost of hash map lookups and reified generics. In practice, the hash map lookup cost seems to be significantly less.

Strictly on principle though, it would be nice to have a `data` field to avoid the `HashMap` when the map is not necessary.

> adding multiple, application-specific fields

Aside from something like a single `data` field, I'm opposed to the idea, even though it may wind up being necessary at some point. My reasons:

1. I find it *very* ugly to pollute general purpose libraries with application specific concerns. If you add something that would really help out with the Dart backend, *all* of your users will be stuck looking at the mess.
2. The typing/module dependency issue you mentioned
3. Initialization and null safety concerns: having a `DeclarationModel` attribute would be *great* for me, but the type would have to be `DeclarationModel?` since `ceylon.ast` may be used independent of typechecking. And then, I'd have to `assert(exists d)` all over my code.

The solution to all of this that I've been kicking around for a while (but haven't had time to document) would be to use the super type introductions feature proposed elsewhere. We'd want to polymorphically augment nodes (including covariant refinements of introduced members) in application specific ways. This could be built on top of the "extra info" storage or the single `data` field (introductions are stateless.) But I digress.

> we should definitely add getRaw as counterpart to set. Any ideas for a better name?

Nothing that jumps out as a clear winner. Just things like `untypedGet` or `getUntyped`.

**Comment by lucaswerkmeister** [comment]
I pushed something to branch `108` (which I’ll have to remember to rebase on `1.2.0` before merging).

**Comment by lucaswerkmeister** [comment]
Done in branch `108` and merged into `master`.
