### ISSUE TITLE
make Editor lightning quick

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#111]
Naive use of `ceylon.ast.core::Editor` is too slow to be used in a compiler. So I'd like to explore ideas to make it fast.

* Change default implementations of leaf nodes to return `that`
* Add a method `default Boolean editNode(Node node) => true;` called by default implementations of all non-leaf nodes; return `that` if `false`.
* Other?

[Here's](https://gist.github.com/jvasileff/02175a4e782fa7fad258) a somewhat optimized `Editor` that can help serve as an example. This one runs in a little under twice the time of a simple count-nodes visitor on the SDK. A non-optimized Editor takes about 3 or 4 times as long to run.

The big downside to this approach is that `editNode()` can be complex and serves no purpose other than optimization.

**Comment by lucaswerkmeister** [comment]
First bullet done. Perhaps we could do the second one in a subclass of `Editor`?

**Comment by jvasileff** [comment]
Is there an advantage to having a subclass that outweighs the maintenance overhead?

I'd hazard to guess that a when using the default `editNode() => true`, the overhead of the check would not be measurable.

**Comment by lucaswerkmeister** [comment]
> The big downside to this approach is that `editNode()` can be complex

True, but it can also be simple. I would think that often, a simple `=> is X;` or `=> is X|Y|Z;` would be enough. For known `X`, `Y`, `Z`, this would compile down to an `instanceof` test (or `instanceof || instanceof || …`), and I think I recall reading that HotSpot can often optimize `instanceof` down to a single instruction.

**Comment by lucaswerkmeister** [comment]
The advantage would be to keep `Editor` a bit simpler, but I guess that’s a pretty small advantage

**Comment by jvasileff** [comment]
> True, but it can also be simple

Agreed. And, `editNode()` impls can error on the side of returning `true`, to reduce complexity.

**Comment by lucaswerkmeister** [comment]
Right. So let’s add this…

**Comment by lucaswerkmeister** [comment]
Second bullet also done. Should I leave this issue open for more suggestions, or close it, and you’ll open new issues for new suggestions?

**Comment by jvasileff** [comment]
Great, thanks @lucaswerkmeister!

I'm still interested in any ideas/techniques anyone might have for writing fast Editors, but I'm out of improvement ideas for now, so I'll go ahead and close the issue.
