### ISSUE TITLE
make Editor methods for abstract nodes non-default

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#112]
I can't see any reason for overriding transform methods for "wide" nodes. It seems that this would either be a mistake or at least be a case of very fragile code. Unless there *is* some reason to allow refinements, making them non-default will help clarify the api and reduce bugs.

The same could almost be said for `ImmediateNarrowingTransformer` too, except for that interface, it's useful to refine return types, as `Editor` does.

**Comment by lucaswerkmeister** [comment]
Makes sense. I guess I’ll tag this as “performance”, since non-virtual methods can be slightly faster?

**Comment by lucaswerkmeister** [comment]
> It seems that this would either be a mistake or at least be a case of very fragile code.

Well, there’s [this](https://github.com/ceylon/ceylon.ast/blob/86faa2b1aae6d9404cce816da19860cb967bf58f/source/ceylon/ast/samples/bodyReturnRewrite/RewriteReturnsEditor.ceylon#L66-L68) in the samples.
```ceylon
// shortcuts to do less copying
transformStatement(Statement that) => that;
transformDeclaration(Declaration that) => that;
```
Looks like a hand-written variation of #111, doesn’t it? However, a quick test reveals: replacing `=> that` with `=> nothing` has no effect, the test still passes. So I guess this reinforces the point that whatever you thought you were doing by overriding wide transform methods, you didn’t do it right :D

**Comment by jvasileff** [comment]
Precisely :smile:

**Comment by lucaswerkmeister** [comment]
1. I forgot to update source-gen.
2. This should be done for aliases as well, right?

**Comment by jvasileff** [comment]
> This should be done for aliases as well, right?

WDYM? Not things like `ClassAliasDefinition`, right?

**Comment by lucaswerkmeister** [comment]
No, the precedence aliases like `AssigningExpression`, `DisjoiningExpression` etc.

**Comment by jvasileff** [comment]
Oh, yeah, that makes sense.

**Comment by lucaswerkmeister** [comment]
Oh, and this also breaks the automatic sorting of source-gen, since methods with and without `default` are mixed :/

**Comment by lucaswerkmeister** [comment]
Alright, done now.
