### ISSUE TITLE
Extend extended type syntax

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#117]
For Dart support, we should allow:

- [ ] `extends A.B()`. Here, `B` is an inner class of `A`, so this is an `Extension`, not a `Construction` with an uppercase constructor name. (Presumably, `A.B.C.D()` etc. is also allowed?)
- [ ] `extends A.B.c()`. This is a `Construction` – `c` is a constructor of `A.B`.

See also ceylon/ceylon#6377.

**Comment by jvasileff** [comment]
> Presumably, A.B.C.D() etc. is also allowed?

Yes. This typechecks:

`JavaA.java`
```java
public interface JavaA {
    interface B {
        interface C {
            class D {}
        }
    }
}
```
`run.ceylon`
```ceylon
class Crazy() extends JavaA.B.C.D() {}
```

**Comment by lucaswerkmeister** [comment]
I’m asking if it’s allowed in Dart – the Java backend doesn’t use this module :)

**Comment by jvasileff** [comment]
But people who use the Java backend do use this module!

I don't currently plan to use more than one level of type nesting (i.e. `A.B()`) in Dart. Dart doesn't actually support inner classes, but I'm "manufacturing" them when generating inerop models (https://github.com/jvasileff/ceylon-dart/issues/8#issuecomment-186280615)

**Comment by lucaswerkmeister** [comment]
Are you going to be analyzing Java-backend code with `ceylon.ast`? I’m pretty sure this is not the only Java interop feature `ceylon.ast` doesn’t support…

**Comment by jvasileff** [comment]
Yes. I'd like to be able to compile all valid Ceylon code, since there might be:

```
native("jvm") shared class Crazy() extends JavaA.B.C.D() {}
```

(granted, it's unlikely that code will actually exist)

Does `ceylon.ast` not support all of Ceylon 1.2.2 syntax?

**Comment by lucaswerkmeister** [comment]
It supports all Ceylon 1.2.2 syntax *in the spec* (as far as I know). The JVM backend goes quite a bit beyond that, and I don’t really see why I have to support all of that if this module isn’t part of the JVM backend.

**Comment by jvasileff** [comment]
Ok. I just wasn't aware of anything that ceylon.ast doesn't support. But I would argue, if there is something, it should support it. Beyond compiling Dart, I might want to use `ceylon.ast` for a code generator that needs to output `extends JavaA.B.C.D()`.

**Comment by lucaswerkmeister** [comment]
Actually, I get a syntax error for this:
>source/tmp/run.ceylon:2: error: incorrect syntax: no viable alternative at token 'c'
```ceylon
class D() extends A.B.c() {}
                      ^
```
error: incorrect syntax: no viable alternative at token end of file

@jvasileff is `A.B.c()` something that makes sense in Dart, or should I only add support for `A.B.C()`?

**Comment by jvasileff** [comment]
@lucaswerkmeister I think we can do without `A.B.c()` since:

* Dart doesn't have inner or nested classes
* Java doesn't have named constructors
* Ceylon doesn't have static members

**Comment by jvasileff** [comment]
Wait, forget what I just said!

Of course, I'm making fake member classes. Seems like this is needed. Lemme take a closer look.

**Comment by lucaswerkmeister** [comment]
Sure. It’s not like I just discarded the related part of my working tree :(

**Comment by jvasileff** [comment]
Oh that stinks.

**Comment by lucaswerkmeister** [comment]
Well, it was only a few lines, I hadn’t gotten to the RedHat transformation yet.

**Comment by lucaswerkmeister** [comment]
Alright, the `Extension` half is ready… shall I commit it now and we’ll see later if that’s enough to close this issue?

**Comment by jvasileff** [comment]
Ok, I see the syntax error too. For reference:

> error: incorrect syntax: no viable alternative at token 'c'
```
class X() extends A.B.c() {
                      ^
```

I guess it's really up to @gavinking if he'd like to support this. The workaround for extending a Dart named constructor, which isn't too bad, is to use an `import` alias.

**Comment by jvasileff** [comment]
@lucaswerkmeister great! Sounds good.
