### ISSUE TITLE
permit empty elements in ImportElements

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#120]
Basically, I think, remove from `ImportElements`:

```ceylon
    "Import elements may not be empty"
    assert (nonempty children_ = concatenate(elements, emptyOrSingleton(wildcard)));
```

The problem I ran into was that for JavaScript and Dart, the following:
```ceylon
import java.nio {
    JavaByteBuffer=ByteBuffer {
        // allocateJavaByteBuffer=allocate
    }
}
```
is "valid enough" to pass type checking and compile without error (and does, indeed on JS), since `java.nio` is ignored since it is `native("jvm")`. The "Import elements may not be empty" error is not a `RecognitionError`.

See also https://github.com/ceylon/ceylon/issues/6501

Edit: actually, I guess I'm not sure about the error type.

**Comment by jvasileff** [comment]
Thinking out loud, I wonder what *other* problems like this I might run into.

Currently, if there are typechecker errors, I don't attempt to create a `ceylon.ast`. This protects me from `AssertionError`s, *mostly*.

**Comment by lucaswerkmeister** [comment]
Should I do this in 1.3.0?

**Comment by jvasileff** [comment]
I vote yes!
