### ISSUE TITLE
allow Tuple MatchCase for new switch on tuple feature

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#125]
`MatchCase`s with `Tuple`s literals like `case ([1, 2])` are now supported by the typechecker. See https://github.com/ceylon/ceylon/issues/4127#issuecomment-246292682

**Comment by lucaswerkmeister** [comment]
Fix on branch `tupleMatchCase`, awaiting merge of ceylon/ceylon branch `4127`.

**Comment by jvasileff** [comment]
👍

**Comment by lucaswerkmeister** [comment]
(Note to self: don’t forget to add this to the CHANGES wiki page when merged. I don’t want to do that yet in case something changes.)
