### ISSUE TITLE
bad example in docs for MemberMeta

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#130]
This isn't (currently) allowed:

```ceylon
noop(`system.milliseconds`);
// incorrect syntax: error at '.'
```
see https://modules.ceylon-lang.org/repo/1/ceylon/ast/core/1.3.1/module-doc/api/MemberMeta.type.html

FTR, `\Isystem.milliseconds` is accepted, if someone really wanted to do that...

**Comment by lucaswerkmeister** [comment]
Huh, yeah, `system` is clearly not a `PrimaryType`… not sure where I got that from.

**Comment by lucaswerkmeister** [comment]
Actually, there is a test for `` `\Isystem.milliseconds` ``… but I think I still prefer to remove the example altogether than to fix it like that.
