### ISSUE TITLE
Add support for interpolated assertion messages

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#131]
See ceylon/ceylon#3692 and ceylon/ceylon@ce9eb29b4306a01734811bc2833092eefb4f2d46.

**Comment by lucaswerkmeister** [comment]
The typechecker change in `Ceylon.nodes` is very simple, though slightly odd: *any* anonymous annotation (doc string) can now be a string template instead, and assertions still have a full annotation list. However, the grammar doesn’t actually produce this: due to the way the lookahead rules are written, declarations still can’t be documented with string templates, and assertions can no longer have regular annotations. So I think the much better solution in `ceylon.ast` is to change `Assertion` to have a `StringLiteral|StringTemplate` member, replacing the `annotations` member.

**Comment by lucaswerkmeister** [comment]
`StringLiteral|StringTemplate?` of course, to allow a missing message.

**Comment by lucaswerkmeister** [comment]
@jvasileff now the discussion’s *really* over ;)

**Comment by jvasileff** [comment]
Given the apparent finality of the matter, I'm glad you made the message optional, benefiting the lazy non-documenting types.

**Comment by lucaswerkmeister** [comment]
Well if there’s anything wrong with the design we can still change it of course… anything standing out to you?

**Comment by jvasileff** [comment]
No :)

**Comment by lucaswerkmeister** [comment]
Reopening since we now have a spec for this (https://github.com/ceylon/ceylon/commit/e1d977be9c46941e93b4d23e89dd908147a53e84) and so the names are wrong :(
