### ISSUE TITLE
Include source code in published ceylon-docs

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.ast#132]
If I'm not mistaken, this would mean changing the doc gen command to:

    ceylon doc --source-code ceylon.ast.{core,create,redhat,samples}

in https://github.com/ceylon/ceylon.ast/wiki/Release-process

**Comment by lucaswerkmeister** [comment]
Oh, I need to do something for that? I thought it used the uploaded source archive…

**Comment by lucaswerkmeister** [comment]
Done, thanks for the info! I’ve also added `--source-code` to the `ceylon doc` invocation in the release document, so hopefully this shouldn’t be an issue next time either.
