### ISSUE TITLE
 Add support for new destructuring syntax

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#138]
See ceylon/ceylon#7220.

Question: What do we do about the old syntax? Apparently the compiler still supports it for a while; do we want to have two kinds of destructuring expressions in the AST?

**Comment by lucaswerkmeister** [comment]
> What do we do about the old syntax?

Unless I hear any objections, I think I’ll go with the easier route of only having one type of destructuring in `ceylon.ast.core`: the new syntax. `ceylon.ast.redhat` will probably map old-style destructuring to that, but it’ll be a lossy conversion.

**Comment by jvasileff** [comment]
So you would be able to consume all valid Ceylon programs, but only represent and produce non-deprecated destructurings? That sounds like a reasonable compromise to me.

**Comment by jvasileff** [comment]
In fact, that sounds quite nice for the use-cases I can think of. Anyone using `ceylon.ast` to read or analyze a program will have one less thing to worry about.

**Comment by lucaswerkmeister** [comment]
Hm, then you won’t like to hear that I’m already starting to second-guess myself on this :D

Because it looks like in `ceylon.ast.core` this will be a new node type either way, called `LetStatement`, analogous to `LetExpression`, so from that standpoint perhaps I might as well leave `Destructure` around? But the conversion is likely to be the hairier part, and that will probably be simpler if `Destructure` is removed.

**Comment by jvasileff** [comment]
I'm not sure I have a horse in this race, but I think the important thing is that it should be possible to consume all valid Ceylon source files, one way or another.

**Comment by luolong** [comment]
I am not sure, conversion should be the concern of `ceylon.ast`

**Comment by lucaswerkmeister** [comment]
> Because it looks like in `ceylon.ast.core` this will be a new node type either way, called `LetStatement`, analogous to `LetExpression`

Hm, nevermind, the spec still calls it `Destructure`.

**Comment by lucaswerkmeister** [comment]
The parser produces equivalent ASTs for both syntaxes anyways, so we get support for the old syntax almost for free.
