### ISSUE TITLE
Support for Type[length]

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#52]
We need to support ceylon/ceylon-spec#1041.

I’ll probably wait until it’s properly specified though.

**Comment by lucaswerkmeister** [comment]
Alright, these have been added to the spec as
```antlr
TupleType: "[" TypeList "]" | PrimaryType "[" DecimalLiteral "]"
```
How do we model them?

My best idea currently would be to turn `TupleType` into an abstract class with the two subclasses `ListTupleType` and `LengthTupleType`, but I don’t really like that much.

**Comment by jvasileff** [comment]
A three class solution sounds right to me.

**Comment by lucaswerkmeister** [comment]
I implemented exactly what I proposed in the above comment, since I haven’t been able to think of anything better (neither layout nor name) in the meantime. Done.

**Comment by lucaswerkmeister** [comment]
Fuck me, I already did this half a year ago in c4329c18957c55ec5a15e82d1b3dc05f58aa708f without mentioning this issue. So now I have *two* implementations of this and need to decide which to keep.

**Comment by lucaswerkmeister** [comment]
So we currently have two implementations of this:

1. `SequentialType` has an optional `length` child of type `IntegerLiteral`
2. `TupleType` is an abstract supertype of `ListTupleType` (previously `TupleType`) and `LengthTupleType` (`PrimaryType` plus `IntegerLiteral`).

Which one should we keep? 1 is closer to the RedHat AST, while 2 is slightly closer to the spec.

I think I lean slightly towards 2. Any other opinions?

**Comment by lucaswerkmeister** [comment]
What’s really mysterious, by the way, is this: both implementations have tests, and all tests currently pass. I don’t understand how this is possible, since both versions *should* erase to the same RedHat AST – and consequently, it shouldn’t be possible to distinguish between them, and both versions should be converted back to the same version (I would expect 2 due to [this](https://github.com/ceylon/ceylon.ast/commit/8b6c3fdfa0e59b3638a564358cf025a31e52fc2d#diff-1bd54f6a20fbe388100cff6d21eb57a3R34)). I’ll definitely have to look into this too.

**Comment by jvasileff** [comment]
I'd lean towards 2, I think, since it is indeed a `ceylon.language::Tuple`. But of course, that's not absolute. Sequence, Sequential, and Tuple are often used interchangeably. Notably, in `ceylon.ast`, `ceylon.language::Empty` is represented by a `TupleType`, even though it is not a `ceylon.language::Tuple`.

Oh, wait, no. I change my vote. It seems `SequentialType` is of the form `Type[whatever]` and `TupleType` is of the form `[whatever]`. So `String[2]` would be of the `SequentialType` form.

**Comment by lucaswerkmeister** [comment]
I guess that from the viewpoint that `ceylon.ast` is about syntax, not semantics, 1 makes more sense…

**Comment by lucaswerkmeister** [comment]
Found out why the tests work: `primaryType` and `type` test objects are completely missing. No one is testing `typeToCeylon`. Probably related to #100. *screams in horror*

I’ll add those, check that the tests fail as they should, then remove solution 2.

**Comment by lucaswerkmeister** [comment]
Done again. Once I fixed the tests (9487f13), they indeed failed as expected, so now I know they work :) and once I removed 2 in ae4c94d, they worked again.

**Comment by lucaswerkmeister** [comment]
Reopening again because there’s one last open question. Per spec, only decimal integer literals are allowed, not binary or hex ones:
```antlr
TupleType: "[" TypeList "]" | PrimaryType "[" DecimalLiteral "]"
```
I enforced this in implementation 2 ([here](https://github.com/ceylon/ceylon.ast/blob/8b6c3fdfa0e59b3638a564358cf025a31e52fc2d/source/ceylon/ast/core/LengthTupleType.ceylon#L21)), but not in implementation 1. Should I add it to implementation 1? It depends on whether this is considered a syntax error or a different error. It looks like a syntax error in the spec, but the compiler grammar accepts any integer literal, and instead of a syntax error you get an “error: must be a positive decimal integer”, probably from `LiteralVisitor`.

I could live with both; probably leaning slightly towards not adding the check (but documenting that).

**Comment by lucaswerkmeister** [comment]
Not checking.
