### ISSUE TITLE
constructors

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.ast#71]
We need to support constructors. See ceylon/ceylon-spec#796.

EDIT: Let’s make a task list.

- [x] `ConstructorDefinition` (I think we’ll inline the spec’s `ConstructorHeader`)
- [x] ~~Update `ClassBody` (see ceylon/ceylon-spec#1194)~~ – obsolete, since `ConstructorDefinition` extends `Declaration`
- [x] ~~`ConstructorExpression`~~ – nope, that’s a subset of `MemberExpression`.
- [x] ~~`ConstructorMeta`~~ – strictly speaking, not a subset of `TypeMeta` per-spec, but the RedHat compiler can’t parse `memberQualifier.ConstructorName` at all, so we’ll omit it too
- [x] `ConstructorDec`, and don’t forget to update the `Dec.keyword` documentation
- [x] Update `ExtendedType` (ceylon/ceylon-spec#1126) (I think we’ll inline the spec’s `SuperclassOrConstructor`) – edit: actually, update `ClassInstantiation`, which both `ExtendedType` and `ClassSpecifier` wrap
- [x] Update `ClassDefinition` (optional parameters)
- [x] `ceylon.ast.create`

**Comment by lucaswerkmeister** [comment]
Also includes ceylon/ceylon-spec#1126.

**Comment by lucaswerkmeister** [comment]
So what’s the supertype of `ConstructorDefinition`? Per spec, a `ConstructorDefinition` can only appear within a `ClassBody`, not within an `InterfaceBody` or `Block`. However, without complement types (`{Statement|Declaration~ConstructorDefinition*} content`), this would be a bit ugly to enforce within the type system… unless we say that `ConstructorDefinition` *doesn’t* extend `Declaration`.

But that’s probably too weird. Perhaps that’s a restriction we can either do via assertions, or just omit from ` ceylon.ast` altogether.

**Comment by lucaswerkmeister** [comment]
Regarding `ExtendedType`: I think we’ll get rid of `ClassInstantiation` and inline it into `ClassSpecifier` (unchanged) and `ExtendedType` (with the added possibility of a `TypeNameWithTypeArguments` qualifier).

**Comment by lucaswerkmeister** [comment]
Actually… the compiler completely accepts:
```ceylon
class C {
    shared new C() {}
    shared new D() {}
}
class D() => C.D();
```
even though, per the spec, a `ClassSpecifier` can only be qualified by `super`:
> ```antlr
ClassSpecifier: "=>" ("super" ".")? TypeNameWithArguments PositionalArguments
```

So perhaps that rule just wasn’t updated, and in fact `ClassSpecifier` and `ExtendedType` still have the same syntax, meaning we can keep `ClassInstantiation`?

@gavinking?

**Comment by gavinking** [comment]
@lucaswerkmeister fixed.

**Comment by lucaswerkmeister** [comment]
Thanks, then I’ll keep `ClassInstantiation`.

**Comment by lucaswerkmeister** [comment]
Alright, I think we’re done here! I hope I haven’t forgotten anything…
